source: 'sources/'
destination: 'destination/'
templates: 'templates/'

sites:
  mossportal: 'Moss portal'

entities:
  asset:
    file name: 'assets_mapping_template.xlsx'
    entity name: 'File (file)'
  nodes:
    file name: 'content_type_mapping_template.xlsx'
    entity name: 'Node (node)'
