source: 'sources/'
destination: 'destination/'
templates: 'templates/'

sites:
  easme: 'Easme site'

entities:
  asset:
    file name: 'assets_mapping_template.xlsx'
    entity name: 'File (file)'
  nodes:
    file name: 'content_type_mapping_template.xlsx'
    entity name: 'Content (node)'